# Generated by Django 3.2.6 on 2022-11-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20221107_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Parliamentary_Constituency',
        ),
    ]
