# Generated by Django 3.2.6 on 2022-11-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_rename_city_parliamentary_constituency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parliamentary_Constituency',
            new_name='City',
        ),
    ]
